### PR TITLE
Updated the table example adding usage of multirow and multicolumn

### PR DESCRIPTION
**Pull request by CptGit**
Hmm...Maybe someone else needs to know how to make a complex table.

### CODE REVIEW

**Comment by sheng-qiang** [comment]
some useless files like  .aux and .log are inclueded. Make sure your commit has exclueded them.

By the way, the complex table example in main.tex is good, but the simple table example should also be reserved for common use.

You'd better create a new pull request.

P.S. You make a typo in annotation for "multirow". The word "multicolum" should be "multicolumn".

**Comment by sheng-qiang** [comment]
It's great to have a .gitignore file, which I forgot to create.

**Comment by CptGit** [comment]
Good. I'm gonna copy my draft into the template. Good luck to myself.

**Comment by sheng-qiang** [comment]
BTW, a little ref mistake was found in Chapter1. It' been corrected in the latest commit.

**Pull request merged**
